# Generated by Django 5.0.4 on 2024-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('locality', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('AS', 'Ashanti'), ('GA', 'Accra'), ('WR', 'Western'), ('OR', 'Oti'), ('NR', 'Northern'), ('UW', 'Upper West'), ('UE', 'Upper East')], max_length=2)),
                ('house_number', models.CharField(max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('payment_options', models.CharField(choices=[('M', 'MoMo'), ('P', 'PayPal')], max_length=1)),
            ],
        ),
    ]
