# Generated by Django 5.0.4 on 2024-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreply',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
